name: latexindent Continuous Integration Workflow

on:
  push:
    branches: [main]

jobs:
  README-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Fetch latexindent
        run: |
          id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cmhughes/latexindent.pl/releases/latest |
            jq '.assets[] | select(.name=="latexindent-linux") | .id')
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cmhughes/latexindent.pl/releases/assets/$id \
            -o latexindent
          chmod +x latexindent

      - name: Fetch latexindent config file
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Tarang74/LaTeX-Submodule/contents/latexindent.yaml |
            jq -r '.content' | base64 -d > latexindent.yaml

      - name: Format tex files
        run: |
          for i in $(find . -type f -name "*tex"); do
            [ -f "$i" ] || break
            ./latexindent -c Debug/ indent.log -w -m -l ./latexindent.yaml "$i"
          done

      - name: Format tikz files
        run: |
          for i in $(find . -type f -name "*tikz"); do
            [ -f "$i" ] || break
            ./latexindent -c Debug/ indent.log -w -m -l ./latexindent.yaml "$i"
          done

      - name: Delete latexindent
        run: |
          rm latexindent latexindent.yaml

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      - name: Commit and push changes
        run: |
          if [[ -z "$(git status --porcelain $STATUS_ARGS $PATHSPEC)" ]]; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "latexindent CI"
            git push
          fi
